# Generated by Django 4.2.26 on 2025-11-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_maintenancerecord_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
