# Generated by Django 4.2.26 on 2025-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipment_manufacturer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='inventory_e_name_3aaa43_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['manufacturer'], name='inventory_e_manufac_260045_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category'], name='inventory_e_categor_8eb76f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['type'], name='inventory_e_type_b12a35_idx'),
        ),
    ]
